dashboard:
    link:
        name:
            title:
                controller:
                    action:
                        dashboard:
                            link:
                                name:
                                    title:
                                        controller:
                                            finally: yay
