#
#   Define this Controller's Actions
#
actions:
    #
    #   Default Action (index)
    #
    index:
        friendly_name: 'Account Management'
        
        link:
            name: 'list samba accounts'
            title: 'List All Accounts'
            action: index

        image:
            name: users.png
            alt: 'List Accounts Icon'
            
    #
    #   Show Only Users
    #
    user:
        friendly_name: 'User Management'
        
        link:
            name: 'list samba users'
            title: 'List Samba Users'
            action: user

        image:
            name: user-white.png
            alt: 'List Users Icon'
            
    #
    #   Show Only Groups
    #
    group:
        friendly_name: 'Group Management'
        
        link:
            name: 'list samba groups'
            title: 'List Samba Groups'
            action: group

        image:
            name: user-business.png
            alt: 'List Groups Icon'
            
    #
    #   Show Only Groups
    #
    adduser:
        friendly_name: 'Add a User'
        
        link:
            name: 'add a new user'
            title: 'Add a New User to the Account Database'
            action: adduser

        image:
            name: user-plus.png
            alt: 'Add New User Icon'
            
    #
    #   Show Only Groups
    #
    addgroup:
        friendly_name: 'Add a Group'
        
        link:
            name: 'add a new group'
            title: 'Add a New Group to the Account Database'
            action: addgroup

        image:
            name: users-plus.png
            alt: 'Add New Group Icon'
            
    #
    #   Show Only Groups
    #
    remove:
        friendly_name: 'Remove a User or Group'
        
        link:
            name: 'remove user/group'
            title: 'Remove a User or Group from the Account Database'
            action: remove

        image:
            name: user-minus.png
            alt: 'List Groups Icon'
            
#
#   Toolbar Actions
#
toolbar:
    index:
        - adduser
        - addgroup
        - remove
        
    user:
        - adduser
        - remove
        
    group:
        - addgroup
        - remove
            
#
#   Dashboard Actions and Title
#
dashboard:
    link:
        name: 'Account Management'
        title: 'Go to the Account Management Area'
        action: index

    image: 
        name: users.png
        alt: 'Account Management Icon'

        
    #
    #
    #
    actions:
        - index
        - user
        - group
        
#
#   Controller Information
#
controller:
    is_advanced: False