##
##   Define this Controller's Actions
##
actions:
    ##
    ##   Default Action (index)
    ##
    index:
        friendly_name: 'Account Management'
        
        link:
            name: 'list samba accounts'
            title: 'List All Accounts'
            action: index

        image:
            name: users.png
            alt: 'List Accounts Icon'
            
    ##
    ##   User "Sub-Controller" Index
    ##
    user:
        friendly_name: 'User Management'
        
        link:
            name: 'list samba users'
            title: 'List Samba Users'
            action: user

        image:
            name: user-white.png
            alt: 'List Users Icon'
            
    ##
    ##   Group "Sub-Controller" Index
    ##
    group:
        friendly_name: 'Group Management'
        
        link:
            name: 'list samba groups'
            title: 'List Samba Groups'
            action: group

        image:
            name: user-business.png
            alt: 'List Groups Icon'
            
    ##
    ##   Add a User
    ##
    adduser:
        friendly_name: 'Add a User'
        
        link:
            name: 'add a new user'
            title: 'Add a New User to the Account Database'
            action: user
            subaction: add

        image:
            name: user-plus.png
            alt: 'Add New User Icon'
            
    ##
    ##   Add a Group
    ##
    addgroup:
        friendly_name: 'Add a Group'
        
        link:
            name: 'add a new group'
            title: 'Add a New Group to the Account Database'
            action: group
            subaction: add

        image:
            name: users-plus.png
            alt: 'Add New Group Icon'

    ##
    ##   Edit a User
    ##
    edituser:
        friendly_name: 'Edit User'
            
    ##
    ##   Edit a Group
    ##
    editgroup:
        friendly_name: 'Edit Group'

    ##
    ##   Remove a User
    ##
    removeuser:
        friendly_name: 'Remove a User'
        
        link:
            name: 'remove user(s)'
            title: 'Remove a User or a list of Users from the Account Database'
            action: user
            subaction: remove
            submit: True
            mass_submit: True
            require_confirm: True
            confirm_message: 'Are you sure you want to remove the selected Users'

        image:
            name: user-minus.png
            alt: 'Remove User Icon'
            
    ##
    ##   Remove a Group
    ##
    removegroup:
        friendly_name: 'Remove a Group'
        
        link:
            name: 'remove a group'
            title: 'Remove a Group from the Account Database'
            action: group
            subaction: remove

        image:
            name: user-minus.png
            alt: 'Remove Group Icon'
            
    ##
    ##  Save Account Information
    ##  Works for Users and Groups 
    ##
    save:
       link:
           name: 'save'
           title: 'Save User or Group Information'
           action: save
           submit: True
       
       image:
           name: disk.png
           alt: 'Save User/Group Icon'

    ##
    ##  Save Account Information but return to edit mode (apply)
    ##  Works for Users and Groups 
    ##
    apply:
       link:
           name: 'apply'     
           title: 'Apply changes and return to this Page'
           action: apply
           submit: True
       
       image:
           name: disk-arrow.png
           alt: 'Apply Changes Icon'

    ##
    ##  Save Account Information and return to the Add screen
    ##
    save-add:
       link:
           name: 'save and add another'     
           title: 'Save these changes and add another User or Group'
           action: save_add
           submit: True
       
       image:
           name: disk-arrow.png
           alt: 'Save and Add Another Icon'

    ##
    ##   Cancel Add/Editing
    ##
    cancel:
       link:
           name: 'cancel'
           title: 'Cancel User/Group creation'
           action: cancel
           submit: True

       image:
           name: minus-circle.png
           alt: 'Cancel Icon'
           

    ##
    ##   Toggle User
    ##
    toggleuser:
        friendly_name: "Toggle a User's Status"
        
        link:
            name: 'toggle user(s)'
            title: "Toggle a User's Status in the Database"
            action: user
            subaction: toggle
            submit: True
            mass_submit: True
            require_confirm: True
            confirm_message: 'Are you sure you want to toggle the status of the selected Users?'

        image:
            name: lock.png
            alt: 'Toggle Status Icon'
            
##
##   Toolbar Actions
##
toolbar:
    index:
        - adduser
        - addgroup
        - user
        - group
        
    user:
        - adduser
        - removeuser
        - toggleuser
        
    group:
        - addgroup
        - removegroup
        
    edituser:
        - save
        - apply
        - cancel
        
    editgroup:
        - save
        - apply
        - cancel
        
    adduser:
        - save-add
        - save
        - apply
        - cancel
        
    addgroup:
        - save-add
        - save
        - apply
        - cancel

##
##   Dashboard Actions and Title
##
dashboard:
    link:
        name: 'Account Management'
        title: 'Go to the Account Management Area'
        action: index

    image: 
        name: users.png
        alt: 'Account Management Icon'

        
    ##
    ##
    ##
    actions:
        - user
        - group
        
##
##   Controller Information
##
controller:
    is_advanced: False
