#
#   Define this Controller's Actions
#
actions:
    #
    #   Default Action (index)
    #
    index:
        friendly_name: 'Account Management'
        
        link:
            name: 'list samba accounts'
            title: 'List All Accounts'
            action: index

        image:
            name: users.png
            alt: 'List Accounts Icon'
            
    #
    #   Show Only Users
    #
    user:
        friendly_name: 'User Management'
        
        link:
            name: 'list samba users'
            title: 'List Samba Users'
            action: user

        image:
            name: user-white.png
            alt: 'List Users Icon'
            
    #
    #   Show Only Groups
    #
    group:
        friendly_name: 'Group Management'
        
        link:
            name: 'list samba groups'
            title: 'List Samba Groups'
            action: group

        image:
            name: user-business.png
            alt: 'List Groups Icon'
            
    #
    #   Add a User
    #
    adduser:
        friendly_name: 'Add a User'
        
        link:
            name: 'add a new user'
            title: 'Add a New User to the Account Database'
            action: adduser

        image:
            name: user-plus.png
            alt: 'Add New User Icon'
            
    #
    #   Add a Group
    #
    addgroup:
        friendly_name: 'Add a Group'
        
        link:
            name: 'add a new group'
            title: 'Add a New Group to the Account Database'
            action: addgroup

        image:
            name: users-plus.png
            alt: 'Add New Group Icon'

    #
    #   Add a User
    #
    edituser:
        friendly_name: 'Edit User'
            
    #
    #   Add a Group
    #
    editgroup:
        friendly_name: 'Edit Group'

    #
    #   Remove a User or Group
    #
    remove:
        friendly_name: 'Remove a User or Group'
        
        link:
            name: 'remove user/group'
            title: 'Remove a User or Group from the Account Database'
            action: remove

        image:
            name: user-minus.png
            alt: 'List Groups Icon'
            
    #
    #   Save Account Information (save)
    #
    save:
       link:
           name: 'save'
           title: 'Save User or Group Information'
           action: save
           submit: True
       
       image:
           name: disk.png
           alt: 'Save Share Icon'

    #
    #   Save Account Information but return to edit mode (apply)
    #
    apply:
       link:
           name: 'apply'     
           title: 'Apply changes and return to this Page'
           action: apply
           submit: True
       
       image:
           name: disk-arrow.png
           alt: 'Apply Changes Icon'

    #
    #   Save Account Information and return to the Add screen (save-add)
    #
    save-add:
       link:
           name: 'save and add another'     
           title: 'Save these changes and add another User or Group'
           action: save_add
           submit: True
       
       image:
           name: disk-arrow.png
           alt: 'Save and Add Another Icon'

    #
    #   Cancel Add/Editing (cancel)
    #
    cancel:
       link:
           name: 'cancel'
           title: 'Cancel User/Group creation'
           action: cancel

       image:
           name: minus-circle.png
           alt: 'Cancel Icon'
            
#
#   Toolbar Actions
#
toolbar:
    index:
        - adduser
        - addgroup
        - remove
        
    user:
        - adduser
        - remove
        
    group:
        - addgroup
        - remove
        
    edituser:
        - save
        - apply
        - cancel
        
    editgroup:
        - save
        - apply
        - cancel
        
    adduser:
        - save-add
        - save
        - apply
        - cancel
        
    addgroup:
        - save-add
        - save
        - apply
        - cancel

#
#   Dashboard Actions and Title
#
dashboard:
    link:
        name: 'Account Management'
        title: 'Go to the Account Management Area'
        action: index

    image: 
        name: users.png
        alt: 'Account Management Icon'

        
    #
    #
    #
    actions:
        - index
        - user
        - group
        
#
#   Controller Information
#
controller:
    is_advanced: False