#
#   Define this Controller's Actions
#
actions:
    #
    #   Default Action (index)
    #
    index:
        friendly_name: 'Help'
        
        link:
            name: 'lookup help'
            title: 'Help'
            action: index

        image:
            name: folders-stack.png
            alt: 'Help Icon'
            
    module:
        friendly_name: 'Context Help'
        
        link:
            name: 'lookup context help'
            title: 'Help for Module'
            action: module

        image:
            name: folders-stack.png
            alt: 'Help Module Icon'
            
            
    about:
        friendly_name: 'About SWAT'
        
        link:
            name: 'about SWAT'
            title: 'About SWAT'
            action: about

        image:
            name: folders-stack.png
            alt: 'About Icon'

#
#   Controller Information
#
controller:
    is_advanced: False