actions:
    - dashboard
    - help
    - context
    - about
    - logout

dashboard:
    link:
        name: 'dashboard'
        title: ''
        controller: dashboard
        action: index
            
help:
    link:
        name: 'help'
        title: ''
        controller: help
        action: index

context:
    link:
        name: 'context help'
        title: ''
        controller: _current_
        action: help
        
about:
    link:
        name: 'about'
        title: ''
        controller: swat
        action: about
        
logout:
    link:
        name: 'logout'
        title: ''
        controller: authentication
        action: logout