#
#   Define this Controller's Actions
#
actions:
    #
    #   Default Action (index)
    #
    index:
        friendly_name: 'Share Management'
        
        link:
            name: 'list shares'
            title: 'List All Shares'
            action: index

        image:
            name: folders-stack.png
            alt: 'List Shares Icon'
            
    #
    #   Default Action (index)
    #
    edit:
        friendly_name: 'Edit Share'
        
        link:
            name: 'edit shares'
            title: 'Edit this Shre'
            action: edit

        image:
            name: folder-pencil.png
            alt: 'Share Edit Icon'
    
    #
    #   Remove Selected Shares (index)
    #
    remove:
        friendly_name: 'Remove Shares'
        
        link:
            name: 'remove shares'
            title: 'Remove selected Shares'
            action: remove
            submit: True
            mass_submit: True
            require_confirm: True
            confirm_message: 'Are you sure you want to Remove the selected Shares'

        image:
            name: folders-minus.png
            alt: 'Mass Share Remove Icon'

    #
    #   Remove Selected Shares (index)
    #
    copy:
        friendly_name: 'Copy Shares'
        
        link:
            name: 'copy shares'
            title: 'Copy selected Shares'
            action: copy
            submit: True
            mass_submit: True
            require_confirm: True
            confirm_message: 'Are you sure you want to Copy the selected Shares'

        image:
            name: folders-plus.png
            alt: 'Mass Share Copy Icon'

    #
    #   Add Share (add)
    #
    add:
        friendly_name: 'Add a New Share'

        link:
            name: 'add share'
            title: 'Add a Share'
            action: add

        image:
            name: folder-plus.png
            alt: 'Add Share Icon'
            
    #
    #   Add Share Using the Assistant (add_assistant)
    #
    add_assistant:
        friendly_name: 'Add a New Share using the Assistant'
        
        link:
            name: 'add share assistant'
            title: 'Add a Share using the Assistant'
            action: add_assistant

        image:
            name: wand.png
            alt: 'Add Share Assistant Icon'
    
    #
    #   Switch View Mode to Assistant (swith_to_assistant)
    #
    switch_to_assistant:
        friendly_name: 'Share Assistant'
        
        link:
            name: 'switch to assistant'
            title: 'Switch to Assistant View'
            action: edit_assistant
        
        image:
            name: wand.png
            alt: 'Add Share Assistant Icon'
            
    #
    #   Save Share Information (save)
    #
    save:
       link:
           name: 'save'
           title: 'Save Share Information'
           action: save
           submit: True
       
       image:
           name: disk.png
           alt: 'Save Share Icon'

    #
    #   Save Share Information but return to edit mode (apply)
    #
    apply:
       link:
           name: 'apply'     
           title: 'Apply changes and return to this Page'
           action: apply
           submit: True
       
       image:
           name: disk-arrow.png
           alt: 'Apply Changes Icon'

    #
    #   Cancel Add/Editing (cancel)
    #
    cancel:
       link:
           name: 'cancel'
           title: 'Cancel Share creation'
           action: cancel

       image:
           name: minus-circle.png
           alt: 'Cancel Icon'
           
#
#   Toolbar Actions
#
toolbar:
    index:
        - add
        - remove
        - copy
    
    add:
        - save
        - apply
        - cancel
        
    edit:
        - save
        - apply
        - cancel
        
#
#   Dashboard Actions and Title
#
dashboard:
    link:
        name: 'Share Management'
        title: 'Go to the Share Management Area'
        action: index

    image: 
        name: folders.png
        alt: 'Share Management Icon'
        
    #
    #
    #
    actions:
        - add
        - index

#
#   Controller Information
#
controller:
    is_advanced: False