#
#   Share Name
#
name:
    type: text
    help: 'Set the Share Name'
    title: "Set this Share's Name"
    name: name
    label: 'Name'
    class: big-text
    id: share-name
    validation: required
    validation-message:
        required: 'You cannot store a Share without a name'
    
#
#   Share Path
#
path:
    type: text
    help: "Sets the path to the directory provided by a file share or used by a printer share. Set automatically in [homes] share to user's home directory, otherwise defaults to  /tmp. Honors the %u (user) and %m (machine) variables."
    title: 'Set the Path to be Shared'
    name: share_path
    label: 'Path'
    class: big-text
    id: share-path
    
    field-ops:
        - path-selection
        - modifiers

    field-ops-descriptor:
        path-selection:
            title: 'Select the Share Location'
            image:
                name: layer-select-point.png
                alt: 'Select Path Icon'
            link:
                controller: share
                action: path
                
        modifiers:
            title: 'Select the Modifiers'
            image:
                name: layer-select-point.png
                alt: 'Select Path Icon'
            list:
                - user
                - machine
            copy-to: share-path
                
    modifiers-descriptor:
        user:
            title: 'User'
            value: '%u'
            
        machine:
            title: 'Machine'
            value: '%m'
                    
                

#
#   Guest OK
#
guest-ok:
    type: checkbox
    help: 'If checked, passwords are not needed for this share.'
    title: 'Check to make this Share Public'
    name: share_guest_ok
    label: 'Public?'
    class: big-margin
    id: share-guest-ok
    disabled: True

#
#   Browsable
#
browsable:
    type: checkbox
    help: 'Allows a share to be announced in browse lists.'
    title: 'Check to make this share Browsable'
    name: share_browsable
    label: 'Browsable?'
    class: big-margin
    id: share-browsable

#
#   Read Only
#
read-only:
    type: checkbox
    help: 'Forces user of a share to do so as the guest account.'
    title: 'Check to make this Share Read Only'
    name: share_read_only
    label: 'Read Only?'
    class: big-margin
    id: share-read-only
    
#
#   Guest Only
#
guest-only:
    type: checkbox
    help: 'Sets a share to read-only.'
    title: 'Check to make this Share Guest Only'
    name: share_guest_only
    label: 'Guest Only?'
    class: big-margin
    id: share-guest-only
    disabled: True

#
#   Create Mask
#
create-mask:
    type: permissions
    help: 'Sets the maximum allowable permissions for new files (e.g., 0755). See also directory mask. To require certain permissions to be set, see force create mask/force directory mask.'
    title: 'Create Mask'
    name: share_create_mask
    permissions-name: create_mask
    
#
#   Directory Mask
#
directory-mask:
    type: permissions
    help: 'Also called directory mode. Sets the maximum allowable permissions for newly created directories. To require certain permissions be set, see the force create mask and force directory mask options'
    title: 'Directory Mask'
    name: share_directory_mask
    permissions-name: directory_mask
    
#
#   Read List
#
read-list:
    type: list
    help: 'List of users that are given read-write access to a read-only share.'
    title: 'Select Users/Groups that will have Read Access to this Share'
    name: share_read_list
    label: 'Read List'
    class: big-text
    id: share-insert-read
    disabled: True
    
    field-ops:
        - manual-add
        - user-group-selection

    field-ops-descriptor:
        user-group-selection:
            title: 'Open User/Group Selection Popup'
            image:
                name: users.png
                alt: 'Select Users/Groups Icon'
            link:
                controller: share
                action: users_groups
                copy-to: share-insert-read-list
                
        manual-add:
            title: 'Add this User/Group. Separate by , to add more than one'
            image:
                name: plus-small.png
                alt: 'Add User/Group Icon'
            link:
                copy-from: share-insert-read
                copy-to: share-insert-read-list
    
#
#   Write List
#
write-list:
    type: list
    help: 'Specifies a list of users given read-only access to a writeable share.'
    title: 'Select Users/Groups that will have Write Access to this Share'
    name: share_write_list
    label: 'Write List'
    class: big-text
    id: share-insert-write
    disabled: True
    
    field-ops:
        - manual-add
        - user-group-selection

    field-ops-descriptor:
        user-group-selection:
            title: 'Open User/Group Selection Popup'
            image:
                name: users.png
                alt: 'Select Users/Groups Icon'
            link:
                controller: share
                action: users_groups
                copy-to: share-insert-write-list
                
        manual-add:
            title: 'Add this User/Group. Separate by , to add more than one'
            image:
                name: plus-small.png
                alt: 'Add User/Group Icon'
            link:
                copy-from: share-insert-write
                copy-to: share-insert-write-list

#
#   Admin List
#
admin-list:
    type: list
    help: 'List of users who will be granted root permissions on the share by Samba.'
    title: 'Select Users/Groups that will have Read Access to this Share'
    name: share_admin_list
    label: 'Admin List'
    class: big-text
    id: share-insert-admin
    disabled: True
    
    field-ops:
        - manual-add
        - user-group-selection

    field-ops-descriptor:
        user-group-selection:
            title: 'Open User/Group Selection Popup'
            image:
                name: users.png
                alt: 'Select Users/Groups Icon'
            link:
                controller: share
                action: users_groups
                copy-to: share-insert-admin-list
                
        manual-add:
            title: 'Add this User/Group. Separate by , to add more than one'
            image:
                name: plus-small.png
                alt: 'Add User/Group Icon'
            link:
                copy-from: share-insert-admin
                copy-to: share-insert-admin-list

#
#   Hosts Allow
#
hosts-allow:
    type: list
    help: 'A list of machines that can access a share or shares. If NULL (the default) any machine can access the share unless there is a hosts deny option.'
    title: 'List of Hostnames that will be able to access this Share'
    name: share_hosts_allow
    label: 'Allowed Hosts'
    class: big-text
    id: share-insert-allowed-hosts
    
    field-ops:
        - manual-add

    field-ops-descriptor:
        manual-add:
            title: 'Add this Host. Separate by , to add more than one'
            image:
                name: plus-small.png
                alt: 'Add Host Icon'
            link:
                copy-from: share-insert-allowed-hosts
                copy-to: share-insert-allowed-hosts-list
                
#
#   Hosts Deny
#
hosts-deny:
    type: list
    help: 'A list of machines that cannot connect to a share or shares.'
    title: 'List of Hostnames that will not be able to access this Share'
    name: share_hosts_deny
    label: 'Denied Hosts'
    class: big-text
    id: share-insert-denied-hosts
    
    field-ops:
        - manual-add

    field-ops-descriptor:
        manual-add:
            title: 'Add this Host. Separate by , to add more than one'
            image:
                name: plus-small.png
                alt: 'Add Host Icon'
            link:
                copy-from: share-insert-denied-hosts
                copy-to: share-insert-denied-hosts-list
