#
#   Share Name
#
name:
    type: text
    help: 'Set the Share Name'
    title: "Set this Share's Name"
    name: name
    label: 'Name'
    class: big-text
    id: share-name
    
#
#   Share Path
#
path:
    type: text
    help: "Sets the path to the directory provided by a file share or used by a printer share. Set automatically in [homes] share to user's home directory, otherwise defaults to  /tmp. Honors the %u (user) and %m (machine) variables."
    title: 'Set the Path to be Shared'
    name: share_path
    label: 'Path'
    class: big-text
    id: share-path
    
    field-ops:
        - path-selection

    field-ops-descriptor:
        path-selection:
            title: 'Select the Share Location'
            image:
                name: layer-select-point.png
                alt: 'Select Path Icon'
            link:
                controller: share
                action: path

#
#   Guest OK
#
guest-ok:
    type: checkbox
    help: 'If checked, passwords are not needed for this share.'
    title: 'Check to make this Share Public'
    name: share_guest_ok
    label: 'Public?'
    class: big-margin
    id: share-guest-ok
    disabled: True

#
#   Browsable
#
browsable:
    type: checkbox
    help: 'Allows a share to be announced in browse lists.'
    title: 'Check to make this share Browsable'
    name: share_browsable
    label: 'Browsable?'
    class: big-margin
    id: share-browsable

#
#   Read Only
#
read-only:
    type: checkbox
    help: 'Forces user of a share to do so as the guest account.'
    title: 'Check to make this Share Read Only'
    name: share_read_only
    label: 'Read Only?'
    class: big-margin
    id: share-read-only
    
#
#   Guest Only
#
guest-only:
    type: checkbox
    help: 'Sets a share to read-only.'
    title: 'Check to make this Share Guest Only'
    name: share_guest_only
    label: 'Guest Only?'
    class: big-margin
    id: share-guest-only
    disabled: True

#
#   Create Mask
#
create-mask:
    type: permissions
    help: 'Sets the maximum allowable permissions for new files (e.g., 0755). See also directory mask. To require certain permissions to be set, see force create mask/force directory mask.'
    title: 'Create Mask'
    name: share_create_mask
    permissions-name: create_mask
    
#
#   Directory Mask
#
directory-mask:
    type: permissions
    help: 'Also called directory mode. Sets the maximum allowable permissions for newly created directories. To require certain permissions be set, see the force create mask and force directory mask options'
    title: 'Directory Mask'
    name: share_directory_mask
    permissions-name: directory_mask

